language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_install:
- mv userProfileForm.jsx UserProfileForm.jsx
script:
  - npm test
  - npm run build
after_success:
  - npm run coveralls