language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_install:
- git mv components/templates/userProfileForm.jsx components/templates/UserProfileForm.jsx
script:
  - npm test
  - npm run build
after_success:
  - npm run coveralls